/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author vaneu
 */
public class HistorialPacientes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HistorialPacientes.class.getName());

    /**
     * Creates new form HistorialPacientes
     */
    public HistorialPacientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        RegistroMascotasCentro = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCondicionesPasadas = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtContactodeEmergencia = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAlergias = new javax.swing.JTextArea();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIngresarNombreMascota = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sideBarRegistroMascotas = new javax.swing.JPanel();
        btnRegistrosMedicosCitas = new javax.swing.JButton();
        btnAgendarcitas = new javax.swing.JButton();
        btnHistorialPaciente = new javax.swing.JButton();

        jScrollPane3.setBorder(null);

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(247, 247, 247));
        jTextArea3.setColumns(20);
        jTextArea3.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea3.setRows(5);
        jTextArea3.setText("Alergias\n");
        jTextArea3.setBorder(null);
        jScrollPane3.setViewportView(jTextArea3);

        jScrollPane5.setBorder(null);

        jTextArea5.setEditable(false);
        jTextArea5.setBackground(new java.awt.Color(247, 247, 247));
        jTextArea5.setColumns(20);
        jTextArea5.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea5.setRows(5);
        jTextArea5.setText("Alergias\n");
        jTextArea5.setBorder(null);
        jScrollPane5.setViewportView(jTextArea5);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.setPreferredSize(new java.awt.Dimension(532, 70));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Hola, Doctor");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logoSmall.jpg"))); // NOI18N
        jLabel18.setText("jLabel3");
        jLabel18.setToolTipText("");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(19, 19, 19))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(4, 4, 4)
                .addComponent(jLabel16)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel9, java.awt.BorderLayout.NORTH);

        RegistroMascotasCentro.setBackground(new java.awt.Color(255, 255, 255));
        RegistroMascotasCentro.setPreferredSize(new java.awt.Dimension(500, 700));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Consultar Historial Paciente");

        jScrollPane1.setBorder(null);

        txtCondicionesPasadas.setEditable(false);
        txtCondicionesPasadas.setBackground(new java.awt.Color(247, 247, 247));
        txtCondicionesPasadas.setColumns(20);
        txtCondicionesPasadas.setForeground(new java.awt.Color(0, 0, 0));
        txtCondicionesPasadas.setRows(5);
        txtCondicionesPasadas.setText("\n");
        txtCondicionesPasadas.setBorder(null);
        jScrollPane1.setViewportView(txtCondicionesPasadas);

        jScrollPane2.setBorder(null);

        txtContactodeEmergencia.setEditable(false);
        txtContactodeEmergencia.setBackground(new java.awt.Color(247, 247, 247));
        txtContactodeEmergencia.setColumns(20);
        txtContactodeEmergencia.setForeground(new java.awt.Color(0, 0, 0));
        txtContactodeEmergencia.setRows(5);
        txtContactodeEmergencia.setBorder(null);
        jScrollPane2.setViewportView(txtContactodeEmergencia);

        jScrollPane4.setBorder(null);

        txtAlergias.setEditable(false);
        txtAlergias.setBackground(new java.awt.Color(247, 247, 247));
        txtAlergias.setColumns(20);
        txtAlergias.setForeground(new java.awt.Color(0, 0, 0));
        txtAlergias.setRows(5);
        txtAlergias.setBorder(null);
        jScrollPane4.setViewportView(txtAlergias);

        btnBuscar.setBackground(new java.awt.Color(143, 175, 148));
        btnBuscar.setFont(new java.awt.Font("Segoe UI Black", 1, 10)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Contacto de emergencia");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Condiciones pasadas");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Alergias");

        txtIngresarNombreMascota.setBackground(new java.awt.Color(247, 247, 247));
        txtIngresarNombreMascota.setForeground(new java.awt.Color(0, 0, 0));
        txtIngresarNombreMascota.setBorder(null);
        txtIngresarNombreMascota.addActionListener(this::txtIngresarNombreMascotaActionPerformed);

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Ingrese el nombre de la mascota");

        javax.swing.GroupLayout RegistroMascotasCentroLayout = new javax.swing.GroupLayout(RegistroMascotasCentro);
        RegistroMascotasCentro.setLayout(RegistroMascotasCentroLayout);
        RegistroMascotasCentroLayout.setHorizontalGroup(
            RegistroMascotasCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroMascotasCentroLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(RegistroMascotasCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscar)
                    .addGroup(RegistroMascotasCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtIngresarNombreMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistroMascotasCentroLayout.createSequentialGroup()
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        RegistroMascotasCentroLayout.setVerticalGroup(
            RegistroMascotasCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroMascotasCentroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIngresarNombreMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );

        getContentPane().add(RegistroMascotasCentro, java.awt.BorderLayout.CENTER);

        sideBarRegistroMascotas.setBackground(new java.awt.Color(255, 255, 250));
        sideBarRegistroMascotas.setPreferredSize(new java.awt.Dimension(150, 350));

        btnRegistrosMedicosCitas.setText("Registro medico de cita");
        btnRegistrosMedicosCitas.setBorder(null);
        btnRegistrosMedicosCitas.addActionListener(this::btnRegistrosMedicosCitasActionPerformed);

        btnAgendarcitas.setText("Agendar Citas");
        btnAgendarcitas.setBorder(null);
        btnAgendarcitas.addActionListener(this::btnAgendarcitasActionPerformed);

        btnHistorialPaciente.setText("Historial de paciente");
        btnHistorialPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHistorialPaciente.addActionListener(this::btnHistorialPacienteActionPerformed);

        javax.swing.GroupLayout sideBarRegistroMascotasLayout = new javax.swing.GroupLayout(sideBarRegistroMascotas);
        sideBarRegistroMascotas.setLayout(sideBarRegistroMascotasLayout);
        sideBarRegistroMascotasLayout.setHorizontalGroup(
            sideBarRegistroMascotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarRegistroMascotasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(sideBarRegistroMascotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnHistorialPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgendarcitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrosMedicosCitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sideBarRegistroMascotasLayout.setVerticalGroup(
            sideBarRegistroMascotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarRegistroMascotasLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnRegistrosMedicosCitas)
                .addGap(18, 18, 18)
                .addComponent(btnAgendarcitas)
                .addGap(18, 18, 18)
                .addComponent(btnHistorialPaciente)
                .addContainerGap(521, Short.MAX_VALUE))
        );

        getContentPane().add(sideBarRegistroMascotas, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIngresarNombreMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngresarNombreMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngresarNombreMascotaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnHistorialPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistorialPacienteActionPerformed

    private void btnRegistrosMedicosCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrosMedicosCitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrosMedicosCitasActionPerformed

    private void btnAgendarcitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarcitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgendarcitasActionPerformed

    public static JButton getBtnAgendarcitas() {
        return btnAgendarcitas;
    }

    public static JButton getBtnBuscar() {
        return btnBuscar;
    }

    public static JButton getBtnHistorialPaciente() {
        return btnHistorialPaciente;
    }

    public static JButton getBtnRegistrosMedicosCitas() {
        return btnRegistrosMedicosCitas;
    }

    public static JTextArea getTxtAlergias() {
        return txtAlergias;
    }

    public static JTextArea getTxtCondicionesPasadas() {
        return txtCondicionesPasadas;
    }

    public static JTextArea getTxtContactodeEmergencia() {
        return txtContactodeEmergencia;
    }

    public static JTextField getTxtIngresarNombreMascota() {
        return txtIngresarNombreMascota;
    }


    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HistorialPacientes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel RegistroMascotasCentro;
    public static javax.swing.JButton btnAgendarcitas;
    public static javax.swing.JButton btnBuscar;
    public static javax.swing.JButton btnHistorialPaciente;
    public static javax.swing.JButton btnRegistrosMedicosCitas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JPanel sideBarRegistroMascotas;
    public static javax.swing.JTextArea txtAlergias;
    public static javax.swing.JTextArea txtCondicionesPasadas;
    public static javax.swing.JTextArea txtContactodeEmergencia;
    public static javax.swing.JTextField txtIngresarNombreMascota;
    // End of variables declaration//GEN-END:variables
}
