/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author vaneu
 */
public class RegistroMedicoCitas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroMedicoCitas.class.getName());

    /**
     * Creates new form RegistroMedicoCitas
     */
    public RegistroMedicoCitas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        navbarRegistroCitas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sideBarRegistroMascotas = new javax.swing.JPanel();
        Registro = new javax.swing.JButton();
        btnAgendarCitas = new javax.swing.JButton();
        btnHistorialdepaciente = new javax.swing.JButton();
        RegistroMascotasCentro = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNombremascota = new javax.swing.JTextField();
        txtServicios = new javax.swing.JTextField();
        txtVacunas = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtRazadelaMascota = new javax.swing.JTextField();
        txtMedicamentosrecetados = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 400));
        setPreferredSize(new java.awt.Dimension(600, 500));
        setResizable(false);

        navbarRegistroCitas.setBackground(new java.awt.Color(255, 255, 255));
        navbarRegistroCitas.setMinimumSize(new java.awt.Dimension(850, 720));
        navbarRegistroCitas.setPreferredSize(new java.awt.Dimension(532, 70));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Hola, Doctor");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logoSmall.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setToolTipText("");

        javax.swing.GroupLayout navbarRegistroCitasLayout = new javax.swing.GroupLayout(navbarRegistroCitas);
        navbarRegistroCitas.setLayout(navbarRegistroCitasLayout);
        navbarRegistroCitasLayout.setHorizontalGroup(
            navbarRegistroCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navbarRegistroCitasLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navbarRegistroCitasLayout.setVerticalGroup(
            navbarRegistroCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarRegistroCitasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(navbarRegistroCitasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navbarRegistroCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navbarRegistroCitasLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(navbarRegistroCitasLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(19, 19, 19))))
        );

        sideBarRegistroMascotas.setBackground(new java.awt.Color(255, 255, 250));
        sideBarRegistroMascotas.setPreferredSize(new java.awt.Dimension(150, 350));

        Registro.setBackground(new java.awt.Color(204, 204, 255));
        Registro.setText("Registro medico de cita");
        Registro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Registro.addActionListener(this::RegistroActionPerformed);

        btnAgendarCitas.setBackground(new java.awt.Color(204, 204, 255));
        btnAgendarCitas.setText("Agendar Citas");
        btnAgendarCitas.setBorder(null);
        btnAgendarCitas.addActionListener(this::btnAgendarCitasActionPerformed);

        btnHistorialdepaciente.setBackground(new java.awt.Color(204, 204, 255));
        btnHistorialdepaciente.setText("Historial del paciente");
        btnHistorialdepaciente.setBorder(null);
        btnHistorialdepaciente.addActionListener(this::btnHistorialdepacienteActionPerformed);

        javax.swing.GroupLayout sideBarRegistroMascotasLayout = new javax.swing.GroupLayout(sideBarRegistroMascotas);
        sideBarRegistroMascotas.setLayout(sideBarRegistroMascotasLayout);
        sideBarRegistroMascotasLayout.setHorizontalGroup(
            sideBarRegistroMascotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarRegistroMascotasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(sideBarRegistroMascotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHistorialdepaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgendarCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        sideBarRegistroMascotasLayout.setVerticalGroup(
            sideBarRegistroMascotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarRegistroMascotasLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnAgendarCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnHistorialdepaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        RegistroMascotasCentro.setBackground(new java.awt.Color(255, 255, 255));
        RegistroMascotasCentro.setPreferredSize(new java.awt.Dimension(30, 350));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Registros medicos de citas");

        txtNombremascota.setBackground(new java.awt.Color(204, 204, 255));
        txtNombremascota.setToolTipText("");
        txtNombremascota.setBorder(null);
        txtNombremascota.addActionListener(this::txtNombremascotaActionPerformed);

        txtServicios.setBackground(new java.awt.Color(204, 204, 255));
        txtServicios.setToolTipText("");
        txtServicios.setBorder(null);
        txtServicios.addActionListener(this::txtServiciosActionPerformed);

        txtVacunas.setBackground(new java.awt.Color(204, 204, 255));
        txtVacunas.setToolTipText("");
        txtVacunas.setBorder(null);
        txtVacunas.addActionListener(this::txtVacunasActionPerformed);

        btnAgregar.setBackground(new java.awt.Color(0, 204, 51));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnCancelar.setBackground(new java.awt.Color(255, 52, 52));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        txtRazadelaMascota.setBackground(new java.awt.Color(204, 204, 255));
        txtRazadelaMascota.setToolTipText("");
        txtRazadelaMascota.setBorder(null);
        txtRazadelaMascota.addActionListener(this::txtRazadelaMascotaActionPerformed);

        txtMedicamentosrecetados.setBackground(new java.awt.Color(204, 204, 255));
        txtMedicamentosrecetados.setToolTipText("");
        txtMedicamentosrecetados.setBorder(null);
        txtMedicamentosrecetados.addActionListener(this::txtMedicamentosrecetadosActionPerformed);

        jLabel5.setText("Nombre de la mascota ( presionar enter para buscar) ");

        jLabel6.setText("Raza de la mascota (editar)");

        jLabel7.setText("Vacunas aplicadas (editar)");

        jLabel8.setText("Servicios (editar)");

        jLabel9.setText("Medicamentos (editar)");

        javax.swing.GroupLayout RegistroMascotasCentroLayout = new javax.swing.GroupLayout(RegistroMascotasCentro);
        RegistroMascotasCentro.setLayout(RegistroMascotasCentroLayout);
        RegistroMascotasCentroLayout.setHorizontalGroup(
            RegistroMascotasCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroMascotasCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegistroMascotasCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistroMascotasCentroLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistroMascotasCentroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(RegistroMascotasCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(RegistroMascotasCentroLayout.createSequentialGroup()
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMedicamentosrecetados, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))))
            .addGroup(RegistroMascotasCentroLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(RegistroMascotasCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(RegistroMascotasCentroLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(RegistroMascotasCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(RegistroMascotasCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtRazadelaMascota)
                                .addComponent(txtNombremascota)
                                .addGroup(RegistroMascotasCentroLayout.createSequentialGroup()
                                    .addGroup(RegistroMascotasCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel7)
                                        .addComponent(txtVacunas, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addGap(0, 41, Short.MAX_VALUE))
        );
        RegistroMascotasCentroLayout.setVerticalGroup(
            RegistroMascotasCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroMascotasCentroLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombremascota, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRazadelaMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtVacunas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(RegistroMascotasCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistroMascotasCentroLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMedicamentosrecetados, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(184, 184, 184))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 171, Short.MAX_VALUE)
                .addComponent(RegistroMascotasCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(navbarRegistroCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sideBarRegistroMascotas, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 45, Short.MAX_VALUE)
                .addComponent(RegistroMascotasCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(navbarRegistroCitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(sideBarRegistroMascotas, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombremascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombremascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombremascotaActionPerformed

    private void txtServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServiciosActionPerformed

    private void txtVacunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVacunasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVacunasActionPerformed

    private void txtRazadelaMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazadelaMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRazadelaMascotaActionPerformed

    private void txtMedicamentosrecetadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicamentosrecetadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicamentosrecetadosActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgendarCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarCitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgendarCitasActionPerformed

    private void RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistroActionPerformed

    private void btnHistorialdepacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialdepacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistorialdepacienteActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistroMedicoCitas().setVisible(true));
    }

    public JPanel getRegistroMascotasCentro() {
        return RegistroMascotasCentro;
    }

    public JButton getBtnAgendarCitas() {
        return btnAgendarCitas;
    }

    public JButton getBtnAgregar() {
        return btnAgregar;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnHistorialdepaciente() {
        return btnHistorialdepaciente;
    }

    public JTextField getTxtMedicamentosrecetados() {
        return txtMedicamentosrecetados;
    }

    public JTextField getTxtNombremascota() {
        return txtNombremascota;
    }

    public  JTextField getTxtRazadelaMascota() {
        return txtRazadelaMascota;
    }

    public JTextField getTxtServicios() {
        return txtServicios;
    }

    public JTextField getTxtVacunas() {
        return txtVacunas;
    }

   
  
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Registro;
    private javax.swing.JPanel RegistroMascotasCentro;
    public static javax.swing.JButton btnAgendarCitas;
    public static javax.swing.JButton btnAgregar;
    public static javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnHistorialdepaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JPanel navbarRegistroCitas;
    public static javax.swing.JPanel sideBarRegistroMascotas;
    public static javax.swing.JTextField txtMedicamentosrecetados;
    public static javax.swing.JTextField txtNombremascota;
    public static javax.swing.JTextField txtRazadelaMascota;
    public static javax.swing.JTextField txtServicios;
    public static javax.swing.JTextField txtVacunas;
    // End of variables declaration//GEN-END:variables
}
