package Vista;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author vaneu
 */
public class RegistroMascotas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroMascotas.class.getName());

    /**
     * Creates new form RegistroMascotas
     */
    public RegistroMascotas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sideBarRegistroMascotas = new javax.swing.JPanel();
        btnRegistro = new javax.swing.JButton();
        btnExpedienteMedico = new javax.swing.JButton();
        RegistroMascotasCentro = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtRaza = new javax.swing.JTextField();
        txtNombreMascota = new javax.swing.JTextField();
        txtVacunasregistrados = new javax.swing.JTextField();
        txtMedicamentosregistrados = new javax.swing.JTextField();
        txtServiciosregistrados = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMedicamentosregistrados1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setPreferredSize(new java.awt.Dimension(532, 70));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Hola,Administrador");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logoSmall.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setToolTipText("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(19, 19, 19))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.NORTH);

        sideBarRegistroMascotas.setBackground(new java.awt.Color(255, 255, 250));
        sideBarRegistroMascotas.setPreferredSize(new java.awt.Dimension(150, 350));

        btnRegistro.setText("Registro");
        btnRegistro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistro.addActionListener(this::btnRegistroActionPerformed);

        btnExpedienteMedico.setText("Expediente Medico");
        btnExpedienteMedico.setBorder(null);
        btnExpedienteMedico.addActionListener(this::btnExpedienteMedicoActionPerformed);

        javax.swing.GroupLayout sideBarRegistroMascotasLayout = new javax.swing.GroupLayout(sideBarRegistroMascotas);
        sideBarRegistroMascotas.setLayout(sideBarRegistroMascotasLayout);
        sideBarRegistroMascotasLayout.setHorizontalGroup(
            sideBarRegistroMascotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarRegistroMascotasLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(sideBarRegistroMascotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(btnExpedienteMedico, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        sideBarRegistroMascotasLayout.setVerticalGroup(
            sideBarRegistroMascotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarRegistroMascotasLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btnRegistro)
                .addGap(27, 27, 27)
                .addComponent(btnExpedienteMedico)
                .addContainerGap(348, Short.MAX_VALUE))
        );

        jPanel1.add(sideBarRegistroMascotas, java.awt.BorderLayout.WEST);

        RegistroMascotasCentro.setBackground(new java.awt.Color(255, 255, 255));
        RegistroMascotasCentro.setPreferredSize(new java.awt.Dimension(30, 350));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Registro de mascotas y su historial");

        txtRaza.setBackground(new java.awt.Color(247, 247, 247));
        txtRaza.setForeground(new java.awt.Color(102, 102, 102));
        txtRaza.setToolTipText("");
        txtRaza.setBorder(null);
        txtRaza.addActionListener(this::txtRazaActionPerformed);

        txtNombreMascota.setBackground(new java.awt.Color(247, 247, 247));
        txtNombreMascota.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreMascota.setToolTipText("");
        txtNombreMascota.setBorder(null);
        txtNombreMascota.addActionListener(this::txtNombreMascotaActionPerformed);

        txtVacunasregistrados.setBackground(new java.awt.Color(247, 247, 247));
        txtVacunasregistrados.setForeground(new java.awt.Color(102, 102, 102));
        txtVacunasregistrados.setToolTipText("");
        txtVacunasregistrados.setBorder(null);
        txtVacunasregistrados.addActionListener(this::txtVacunasregistradosActionPerformed);

        txtMedicamentosregistrados.setBackground(new java.awt.Color(247, 247, 247));
        txtMedicamentosregistrados.setForeground(new java.awt.Color(102, 102, 102));
        txtMedicamentosregistrados.setToolTipText("");
        txtMedicamentosregistrados.setBorder(null);
        txtMedicamentosregistrados.addActionListener(this::txtMedicamentosregistradosActionPerformed);

        txtServiciosregistrados.setBackground(new java.awt.Color(247, 247, 247));
        txtServiciosregistrados.setForeground(new java.awt.Color(102, 102, 102));
        txtServiciosregistrados.setToolTipText("");
        txtServiciosregistrados.setBorder(null);
        txtServiciosregistrados.addActionListener(this::txtServiciosregistradosActionPerformed);

        btnAgregar.setBackground(new java.awt.Color(143, 175, 148));
        btnAgregar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnCancelar.setBackground(new java.awt.Color(228, 134, 134));
        btnCancelar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nombre de la mascota");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Raza de la mascota");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Vacunas Registradas");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Servicios Registrados");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Medicamentos Registrados");

        txtMedicamentosregistrados1.setBackground(new java.awt.Color(247, 247, 247));
        txtMedicamentosregistrados1.setForeground(new java.awt.Color(102, 102, 102));
        txtMedicamentosregistrados1.setToolTipText("");
        txtMedicamentosregistrados1.setBorder(null);
        txtMedicamentosregistrados1.addActionListener(this::txtMedicamentosregistrados1ActionPerformed);

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Numero de telefono del dueño");

        javax.swing.GroupLayout RegistroMascotasCentroLayout = new javax.swing.GroupLayout(RegistroMascotasCentro);
        RegistroMascotasCentro.setLayout(RegistroMascotasCentroLayout);
        RegistroMascotasCentroLayout.setHorizontalGroup(
            RegistroMascotasCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroMascotasCentroLayout.createSequentialGroup()
                .addGroup(RegistroMascotasCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistroMascotasCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(RegistroMascotasCentroLayout.createSequentialGroup()
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(RegistroMascotasCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegistroMascotasCentroLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RegistroMascotasCentroLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtMedicamentosregistrados, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RegistroMascotasCentroLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtServiciosregistrados, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RegistroMascotasCentroLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(RegistroMascotasCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(RegistroMascotasCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(txtRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(RegistroMascotasCentroLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7))
                            .addGroup(RegistroMascotasCentroLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtVacunasregistrados, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RegistroMascotasCentroLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8))
                            .addGroup(RegistroMascotasCentroLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9))))
                    .addGroup(RegistroMascotasCentroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(RegistroMascotasCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMedicamentosregistrados1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        RegistroMascotasCentroLayout.setVerticalGroup(
            RegistroMascotasCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroMascotasCentroLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addGap(13, 13, 13)
                .addGroup(RegistroMascotasCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistroMascotasCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtVacunasregistrados, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(5, 5, 5)
                .addComponent(txtServiciosregistrados, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMedicamentosregistrados, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMedicamentosregistrados1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(RegistroMascotasCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel1.add(RegistroMascotasCentro, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRazaActionPerformed

    private void txtVacunasregistradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVacunasregistradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVacunasregistradosActionPerformed

    private void txtMedicamentosregistradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicamentosregistradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicamentosregistradosActionPerformed

    private void txtServiciosregistradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServiciosregistradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServiciosregistradosActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtNombreMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMascotaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnExpedienteMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpedienteMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExpedienteMedicoActionPerformed

    private void txtMedicamentosregistrados1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicamentosregistrados1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicamentosregistrados1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
 
     java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroMascotas().setVisible(true);
            }
        });
    }
   public JButton getBtnAgregar() {
        return btnAgregar;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnExpedienteMedico() {
        return btnExpedienteMedico;
    }


    public JButton getBtnRegistro() {
        return btnRegistro;
    }

    public JTextField getTxtMedicamentosregistrados() {
        return txtMedicamentosregistrados;
    }

    public JTextField getTxtNombreMascota() {
        return txtNombreMascota;
    }

    public JTextField getTxtRaza() {
        return txtRaza;
    }

    public JTextField getTxtVacunasregistrados() {
        return txtVacunasregistrados;
    }


    public JTextField getTxtServiciosregistrados() {
        return txtServiciosregistrados;
    }

    public static JTextField getTxtTelefonoDuenio() {
        return txtMedicamentosregistrados1;
    }
    
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel RegistroMascotasCentro;
    public static javax.swing.JButton btnAgregar;
    public static javax.swing.JButton btnCancelar;
    public static javax.swing.JButton btnExpedienteMedico;
    public static javax.swing.JButton btnRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel sideBarRegistroMascotas;
    public static javax.swing.JTextField txtMedicamentosregistrados;
    public static javax.swing.JTextField txtMedicamentosregistrados1;
    public static javax.swing.JTextField txtNombreMascota;
    public static javax.swing.JTextField txtRaza;
    public static javax.swing.JTextField txtServiciosregistrados;
    public static javax.swing.JTextField txtVacunasregistrados;
    // End of variables declaration//GEN-END:variables

}